server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
  otel:
    addr: ""
    fraction: 1.0
  app_name: "osync"
  sync_duration: 15
data:
  mysql:
    dsn: root:123456@tcp(127.0.0.1:3306)/test1?charset=utf8&parseTime=True&loc=Local
  tidb:
    dsn: root:123456@tcp(127.0.0.1:3390)/test2?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    user: ""
    pwd: ""
    db_index: 1
